from __future__ import annotations

import hashlib
from dataclasses import dataclass
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date, datetime, time, timedelta, timezone
from typing import Literal, Sequence
from zoneinfo import ZoneInfo

from nt_schwab_bridge.config import OptionPlannerConfig
from nt_schwab_bridge.models import OptionContractSnapshot, OptionProposal, OptionProposalLeg, OptionRight, SignalPayload, SignalRecord
from nt_schwab_bridge.planner import OptionProposalPlanner
from nt_schwab_bridge.schwab_adapter import SchwabApiError, SchwabOptionChainProvider

from market_scanner.config import AppSettings
from market_scanner.models import (
    Bias,
    Candle,
    CandidateAction,
    EquityQuote,
    MarketRegime,
    RegimeSymbolState,
    ScanResult,
    ScanSession,
    ScannerCandidate,
    TickerMetrics,
)
from market_scanner.schwab_ext import SchwabEquityDataClient


ProposalMode = Literal["live", "skip", "simulate"]
AUTO_EXPIRY_LABEL = "AUTO"
AUTO_EXPIRY_LABELS = ("THIS_FRIDAY", "NEXT_WEEK_FRIDAY")


@dataclass(frozen=True)
class ProposalBuildSettings:
    expiry_labels: tuple[str, ...] = ()
    allow_in_the_money_primary: bool | None = None
    max_debit_per_trade: float | None = None
    marketable_limit_offset: float | None = None
    exit_target_percentages: tuple[float, ...] = ()


class MarketScanner:
    def __init__(
        self,
        settings: AppSettings,
        equity_client: SchwabEquityDataClient | None = None,
    ) -> None:
        self.settings = settings
        self.equity_client = equity_client or SchwabEquityDataClient(settings.schwab)
        self.planner_config: OptionPlannerConfig = settings.planner_config()
        self.planner = OptionProposalPlanner(self.planner_config)
        self.option_provider = SchwabOptionChainProvider(
            client=self.equity_client.raw_client,
            planner_config=self.planner_config,
        )

    def scan(
        self,
        as_of: datetime | None = None,
        *,
        use_live_quotes: bool = True,
        include_options: bool = True,
        simulate_options: bool = False,
        build_settings: ProposalBuildSettings | None = None,
        notes: list[str] | None = None,
    ) -> ScanResult:
        scanned_at = _utc(as_of or datetime.now(timezone.utc))
        proposal_mode: ProposalMode = "simulate" if simulate_options else ("live" if include_options else "skip")
        all_symbols = list(dict.fromkeys([*self.settings.scanner.regime_symbols, *self.settings.scanner.symbols]))
        quotes = self._safe_quotes(all_symbols) if use_live_quotes else {}
        metrics_by_symbol = self._metrics_for_symbols(all_symbols, quotes, scanned_at)
        regime = self._market_regime(metrics_by_symbol)
        candidates = [
            self._candidate(symbol, metrics_by_symbol[symbol], regime)
            for symbol in self.settings.scanner.symbols
        ]
        ranked = sorted(candidates, key=lambda item: item.score, reverse=True)
        if proposal_mode != "skip":
            ranked = self._add_top_candidate_proposals(ranked, scanned_at, proposal_mode, build_settings)
        top = ranked[: self.settings.scanner.top_n]
        result_notes = [
            "Generated by Schwab Market Scanner.",
            "Option ideas are proposals only; live orders require explicit gated send confirmation.",
        ]
        if notes:
            result_notes.extend(notes)
        return ScanResult(
            scan_id=_scan_id(scanned_at),
            scanned_at=scanned_at,
            session=_session(scanned_at, self.settings.scanner.timezone),
            universe=self.settings.scanner.symbols,
            regime=regime,
            candidates=ranked,
            top_candidates=top,
            notes=result_notes,
        )

    def _safe_quotes(self, symbols: list[str]) -> dict[str, EquityQuote]:
        try:
            return self.equity_client.get_quotes(symbols)
        except Exception:
            quotes: dict[str, EquityQuote] = {}
            for symbol in symbols:
                try:
                    quotes[symbol] = self.equity_client.get_quote(symbol)
                except Exception:
                    continue
            return quotes

    def _metrics_for_symbols(
        self,
        symbols: list[str],
        quotes: dict[str, EquityQuote],
        scanned_at: datetime,
    ) -> dict[str, TickerMetrics]:
        metrics: dict[str, TickerMetrics] = {}
        max_workers = max(1, min(8, len(symbols)))
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(self._safe_metrics, symbol, quotes.get(symbol), scanned_at): symbol
                for symbol in symbols
            }
            for future in as_completed(futures):
                symbol = futures[future]
                try:
                    metrics[symbol] = future.result()
                except Exception as exc:
                    metrics[symbol] = TickerMetrics(
                        symbol=symbol,
                        data_notes=[f"metrics_unavailable:{exc.__class__.__name__}"],
                    )
        return metrics

    def _safe_metrics(self, symbol: str, quote: EquityQuote | None, as_of: datetime) -> TickerMetrics:
        notes: list[str] = []
        try:
            intraday = self.equity_client.get_intraday_candles(symbol)
        except Exception as exc:
            intraday = []
            notes.append(f"intraday_unavailable:{exc.__class__.__name__}")
        try:
            daily = self.equity_client.get_daily_candles(symbol)
        except Exception as exc:
            daily = []
            notes.append(f"daily_unavailable:{exc.__class__.__name__}")
        metrics = compute_metrics(
            symbol=symbol,
            quote=quote,
            intraday=intraday,
            daily=daily,
            as_of=as_of,
            timezone_name=self.settings.scanner.timezone,
        )
        metrics.data_notes.extend(notes)
        return metrics

    def _market_regime(self, metrics_by_symbol: dict[str, TickerMetrics]) -> MarketRegime:
        states: list[RegimeSymbolState] = []
        for symbol in self.settings.scanner.regime_symbols:
            metrics = metrics_by_symbol.get(symbol) or TickerMetrics(symbol=symbol)
            score, bias, reasons = _regime_score(metrics)
            states.append(RegimeSymbolState(symbol=symbol, bias=bias, score=score, metrics=metrics, reasons=reasons))
        if not states:
            return MarketRegime(bias="unknown", score=0, symbols=[], reasons=["no_regime_symbols"])
        avg = sum(state.score for state in states) / len(states)
        if avg >= 0.75:
            bias: Bias = "bullish"
        elif avg <= -0.75:
            bias = "bearish"
        else:
            bias = "mixed"
        return MarketRegime(
            bias=bias,
            score=round(avg, 4),
            symbols=states,
            reasons=[f"{state.symbol}:{state.bias}:{state.score:g}" for state in states],
        )

    def _candidate(
        self,
        symbol: str,
        metrics: TickerMetrics,
        regime: MarketRegime,
    ) -> ScannerCandidate:
        action, direction, reasons, warnings = classify_candidate(
            metrics,
            regime,
            min_price=self.settings.scanner.min_price,
            min_abs_gap_pct=self.settings.scanner.min_abs_gap_pct,
            min_premarket_volume=self.settings.scanner.min_premarket_volume,
        )
        score = candidate_score(metrics, action, regime)
        return ScannerCandidate(
            rank=0,
            symbol=symbol,
            action=action,
            direction=direction,
            score=score,
            metrics=metrics,
            reasons=reasons,
            warnings=warnings,
            proposals=[],
            proposal_blocked_reasons=[],
        )

    def _add_top_candidate_proposals(
        self,
        ranked: list[ScannerCandidate],
        scanned_at: datetime,
        proposal_mode: ProposalMode,
        build_settings: ProposalBuildSettings | None = None,
    ) -> list[ScannerCandidate]:
        top_symbols = {candidate.symbol for candidate in ranked[: self.settings.scanner.top_n]}
        return [
            self._candidate_with_proposals(candidate, scanned_at, proposal_mode, build_settings)
            if candidate.symbol in top_symbols
            else candidate
            for candidate in ranked
        ]

    def build_selected_candidate_proposals(
        self,
        result: ScanResult,
        symbol: str,
        as_of: datetime | None = None,
        build_settings: ProposalBuildSettings | None = None,
    ) -> ScanResult:
        normalized = symbol.upper().replace("$", "").strip()
        scanned_at = _utc(as_of or datetime.now(timezone.utc))
        selected_found = False
        updated_candidates: list[ScannerCandidate] = []
        for candidate in result.candidates:
            if candidate.symbol.upper() == normalized:
                selected_found = True
                reset_candidate = candidate.model_copy(
                    update={
                        "proposals": [],
                        "proposal_blocked_reasons": [],
                    }
                )
                reset_candidate = self._candidate_with_proposals(reset_candidate, scanned_at, "live", build_settings)
                updated_candidates.append(reset_candidate)
            else:
                updated_candidates.append(candidate)
        if not selected_found:
            raise ValueError(f"Symbol {normalized} is not present in the latest scan.")
        return result.model_copy(
            update={
                "candidates": updated_candidates,
                "top_candidates": updated_candidates[: self.settings.scanner.top_n],
                "notes": list(
                    dict.fromkeys(
                        [
                            *result.notes,
                            _selected_build_note(normalized, build_settings),
                        ]
                    )
                ),
            }
        )

    def _candidate_with_proposals(
        self,
        candidate: ScannerCandidate,
        scanned_at: datetime,
        proposal_mode: ProposalMode,
        build_settings: ProposalBuildSettings | None = None,
    ) -> ScannerCandidate:
        if candidate.direction not in {"long", "short"}:
            return candidate
        proposals: list[OptionProposal] = []
        blocked: list[str] = []
        if proposal_mode == "simulate":
            try:
                record = _signal_record(candidate.symbol, candidate.direction, candidate.metrics, scanned_at)
                proposals, blocked = self._simulated_option_proposals(record, candidate.metrics, scanned_at, build_settings)
            except (SchwabApiError, RuntimeError) as exc:
                blocked = [f"simulated_proposal_generation_error:{exc.__class__.__name__}:{str(exc)[:120]}"]
        else:
            try:
                record = _signal_record(candidate.symbol, candidate.direction, candidate.metrics, scanned_at)
                planner_config = _planner_config_for_build_settings(self.planner_config, build_settings)
                if planner_config is self.planner_config:
                    provider = self.option_provider
                    planner = self.planner
                else:
                    provider = SchwabOptionChainProvider(
                        client=self.equity_client.raw_client,
                        planner_config=planner_config,
                    )
                    planner = OptionProposalPlanner(planner_config)
                chain = list(provider(record))
                underlying = provider.last_underlying_price or candidate.metrics.current_price
                result = planner.plan(record, chain, scanned_at, underlying_price=underlying)
                proposals = result.proposals
                blocked = result.blocked_reasons
            except (SchwabApiError, RuntimeError) as exc:
                blocked = [f"proposal_generation_error:{exc.__class__.__name__}:{str(exc)[:120]}"]
        return candidate.model_copy(
            update={
                "proposals": proposals,
                "proposal_blocked_reasons": blocked,
            }
        )

    def _simulated_option_proposals(
        self,
        record: SignalRecord,
        metrics: TickerMetrics,
        scanned_at: datetime,
        build_settings: ProposalBuildSettings | None = None,
    ) -> tuple[list[OptionProposal], list[str]]:
        chain = self._simulated_option_chain(record, scanned_at)
        planner_config = _simulated_planner_config(_planner_config_for_build_settings(self.planner_config, build_settings))
        planner = OptionProposalPlanner(planner_config)
        result = planner.plan(record, chain, scanned_at, underlying_price=metrics.current_price)
        proposals = [_mark_simulated_proposal(proposal) for proposal in result.proposals]
        blocked = list(result.blocked_reasons)
        if proposals:
            return proposals, blocked
        fallback = _simulated_fallback_proposals(record, chain, metrics, scanned_at)
        if fallback:
            blocked.append("simulated_fallback_after_planner_filters")
            return fallback, list(dict.fromkeys(blocked))
        return [], list(dict.fromkeys([*blocked, "no_simulated_proposals_from_current_chain"]))

    def _simulated_option_chain(self, record: SignalRecord, scanned_at: datetime) -> list[OptionContractSnapshot]:
        symbol = self.planner_config.option_symbol_for(record.payload.symbol)
        if symbol not in self.planner_config.allowed_symbols:
            return []
        right: OptionRight = "CALL" if record.payload.direction == "long" else "PUT"
        local_date = scanned_at.astimezone(ZoneInfo(self.settings.scanner.timezone)).date()
        contracts: list[OptionContractSnapshot] = []
        for expiry in _simulated_replay_expiries(local_date):
            contracts.extend(
                self.equity_client.raw_client.get_option_chain(
                    symbol=symbol,
                    expiration=expiry,
                    contract_type=right,
                )
            )
        return contracts


def compute_metrics(
    *,
    symbol: str,
    quote: EquityQuote | None,
    intraday: list[Candle],
    daily: list[Candle],
    as_of: datetime,
    timezone_name: str,
) -> TickerMetrics:
    tz = ZoneInfo(timezone_name)
    local_as_of = as_of.astimezone(tz)
    daily_sorted = sorted(daily, key=lambda item: item.timestamp)
    intraday_sorted = sorted(
        (candle for candle in intraday if candle.timestamp <= as_of),
        key=lambda item: item.timestamp,
    )
    complete_daily = [
        candle
        for candle in daily_sorted
        if candle.timestamp.astimezone(tz).date() < local_as_of.date()
    ]
    if not complete_daily and daily_sorted:
        complete_daily = daily_sorted[:-1] or daily_sorted
    previous = complete_daily[-1] if complete_daily else None
    sma_source = complete_daily[-200:] if len(complete_daily) >= 200 else complete_daily
    sma200 = sum(candle.close for candle in sma_source) / len(sma_source) if sma_source else None

    target_date = _target_intraday_date(intraday_sorted, local_as_of.date(), tz)
    day_bars = [
        candle
        for candle in intraday_sorted
        if target_date is not None and candle.timestamp.astimezone(tz).date() == target_date
    ]
    premarket_bars = [
        candle
        for candle in day_bars
        if time(4, 0) <= candle.timestamp.astimezone(tz).time().replace(tzinfo=None) < time(9, 30)
    ]
    regular_bars = [
        candle
        for candle in day_bars
        if time(9, 30) <= candle.timestamp.astimezone(tz).time().replace(tzinfo=None) < time(16, 0)
    ]
    usable_bars = day_bars or intraday_sorted
    latest = usable_bars[-1] if usable_bars else None
    quote_price = _quote_reference_price(quote)
    current_price = quote_price or (latest.close if latest else None)
    price_time = quote.timestamp if quote_price and quote and quote.timestamp else (latest.timestamp if latest else None)
    data_notes = _data_freshness_notes(
        as_of=as_of,
        price_time=price_time,
        session=_session(as_of, timezone_name),
    )
    gap_pct = (
        ((current_price - previous.close) / previous.close) * 100
        if current_price is not None and previous is not None and previous.close
        else None
    )
    bid = quote.bid if quote else None
    ask = quote.ask if quote else None
    spread_pct = None
    if bid is not None and ask is not None and ask >= bid and current_price:
        spread_pct = ((ask - bid) / current_price) * 100

    return TickerMetrics(
        symbol=symbol.upper(),
        target_date=target_date,
        current_price=_round(current_price),
        previous_close=_round(previous.close if previous else None),
        previous_high=_round(previous.high if previous else None),
        previous_low=_round(previous.low if previous else None),
        sma200=_round(sma200),
        gap_pct=_round(gap_pct),
        premarket_high=_round(max((bar.high for bar in premarket_bars), default=None)),
        premarket_low=_round(min((bar.low for bar in premarket_bars), default=None)),
        premarket_volume=sum(bar.volume for bar in premarket_bars),
        today_high=_round(max((bar.high for bar in regular_bars), default=None)),
        today_low=_round(min((bar.low for bar in regular_bars), default=None)),
        vwap=_round(_vwap(day_bars)),
        bid=_round(bid),
        ask=_round(ask),
        spread_pct=_round(spread_pct),
        latest_bar_time=latest.timestamp if latest else None,
        data_notes=data_notes,
    )


def _quote_reference_price(quote: EquityQuote | None) -> float | None:
    if quote is None:
        return None
    if quote.bid is not None and quote.ask is not None and quote.bid > 0 and quote.ask >= quote.bid:
        midpoint = (quote.bid + quote.ask) / 2
        spread_pct = ((quote.ask - quote.bid) / midpoint) * 100 if midpoint else 100
        if spread_pct <= 2:
            return midpoint
    for value in (quote.mark, quote.last):
        if value is not None and value > 0:
            return value
    return None


def classify_candidate(
    metrics: TickerMetrics,
    regime: MarketRegime,
    *,
    min_price: float,
    min_abs_gap_pct: float,
    min_premarket_volume: int,
) -> tuple[CandidateAction, str, list[str], list[str]]:
    reasons: list[str] = []
    warnings: list[str] = list(metrics.data_notes)
    if metrics.current_price is None or metrics.previous_close is None or metrics.gap_pct is None:
        return "AVOID", "none", ["missing_price_or_gap_data"], metrics.data_notes
    if metrics.current_price < min_price:
        return "AVOID", "none", [f"price_below_min:{metrics.current_price:g}<{min_price:g}"], metrics.data_notes
    if abs(metrics.gap_pct) < min_abs_gap_pct:
        return "WATCH", "none", [f"gap_below_min:{metrics.gap_pct:g}%"], metrics.data_notes
    if metrics.premarket_volume < min_premarket_volume:
        warnings.append(f"premarket_volume_below_min:{metrics.premarket_volume}<{min_premarket_volume}")

    if metrics.gap_pct > 0:
        reasons.append("gap_up")
        if metrics.current_price and metrics.previous_high and metrics.current_price > metrics.previous_high:
            reasons.append("above_previous_high")
        if metrics.sma200 and metrics.previous_close and metrics.previous_close > metrics.sma200:
            reasons.append("previous_close_above_sma200")
        if regime.bias == "bearish":
            warnings.append("market_regime_bearish_against_call")
            return "WATCH", "none", reasons, warnings
        return "CALL_BIAS", "long", reasons, warnings

    reasons.append("gap_down")
    if metrics.current_price and metrics.previous_low and metrics.current_price < metrics.previous_low:
        reasons.append("below_previous_low")
    if regime.bias == "bullish":
        warnings.append("market_regime_bullish_against_put")
        return "WATCH", "none", reasons, warnings
    return "PUT_BIAS", "short", reasons, warnings


def candidate_score(metrics: TickerMetrics, action: CandidateAction, regime: MarketRegime) -> float:
    base = abs(metrics.gap_pct or 0) * 10
    volume_score = min(25.0, (metrics.premarket_volume or 0) / 20_000)
    action_bonus = 20.0 if action in {"CALL_BIAS", "PUT_BIAS"} else 0.0
    regime_bonus = 5.0 if regime.bias != "mixed" else 0.0
    return round(base + volume_score + action_bonus + regime_bonus, 4)


def _regime_score(metrics: TickerMetrics) -> tuple[float, Bias, list[str]]:
    score = 0.0
    reasons: list[str] = []
    if metrics.current_price is None or metrics.previous_close is None:
        return 0, "unknown", ["missing_regime_price"]
    if metrics.current_price > metrics.previous_close:
        score += 1
        reasons.append("above_previous_close")
    elif metrics.current_price < metrics.previous_close:
        score -= 1
        reasons.append("below_previous_close")
    if metrics.vwap:
        if metrics.current_price > metrics.vwap:
            score += 0.5
            reasons.append("above_vwap")
        elif metrics.current_price < metrics.vwap:
            score -= 0.5
            reasons.append("below_vwap")
    if metrics.premarket_high and metrics.current_price > metrics.premarket_high:
        score += 0.5
        reasons.append("above_premarket_high")
    if metrics.premarket_low and metrics.current_price < metrics.premarket_low:
        score -= 0.5
        reasons.append("below_premarket_low")
    if score >= 0.75:
        return round(score, 4), "bullish", reasons
    if score <= -0.75:
        return round(score, 4), "bearish", reasons
    return round(score, 4), "mixed", reasons


def _signal_record(symbol: str, direction: str, metrics: TickerMetrics, scanned_at: datetime) -> SignalRecord:
    payload = SignalPayload(
        strategy="SchwabMarketScanner",
        symbol=symbol,
        direction=direction,
        qty=1,
        underlying_price=metrics.current_price,
        timeframe="1m",
        timestamp=scanned_at,
        signal_type="scanner_gap",
        source_indicator="premarket_gap_scanner",
        tags=["scanner", "gap", direction],
        notes=", ".join(metrics.data_notes),
    )
    signal_id = hashlib.sha256(f"{symbol}|{direction}|{scanned_at.isoformat()}".encode("utf-8")).hexdigest()[:12]
    return SignalRecord(
        id=f"scan_{signal_id}",
        payload=payload,
        received_at=scanned_at,
        execution_mode="dry_run",
    )


def _planner_config_for_build_settings(
    config: OptionPlannerConfig,
    build_settings: ProposalBuildSettings | None,
) -> OptionPlannerConfig:
    if build_settings is None:
        return config
    updates: dict[str, object] = {}
    if build_settings.expiry_labels:
        updates["expiries"] = _resolved_build_expiry_labels(build_settings.expiry_labels)
    if build_settings.allow_in_the_money_primary is not None:
        updates["allow_in_the_money_primary"] = bool(build_settings.allow_in_the_money_primary)
    if build_settings.max_debit_per_trade is not None:
        updates["max_debit_per_trade"] = float(build_settings.max_debit_per_trade)
    if build_settings.marketable_limit_offset is not None:
        updates["marketable_limit_offset"] = float(build_settings.marketable_limit_offset)
    if build_settings.exit_target_percentages:
        updates["exit_target_percentages"] = list(build_settings.exit_target_percentages)
    if not updates:
        return config
    return config.model_copy(deep=True, update=updates)


def _resolved_build_expiry_labels(labels: Sequence[str]) -> list[str]:
    resolved: list[str] = []
    for label in labels:
        normalized = label.upper().strip().replace(" ", "_")
        if normalized == AUTO_EXPIRY_LABEL:
            resolved.extend(AUTO_EXPIRY_LABELS)
        elif normalized:
            resolved.append(normalized)
    return list(dict.fromkeys(resolved))


def _selected_build_note(symbol: str, build_settings: ProposalBuildSettings | None) -> str:
    parts = [f"Built option proposals only for selected symbol {symbol}"]
    if build_settings is not None:
        if build_settings.expiry_labels:
            parts.append(f"expiry {', '.join(build_settings.expiry_labels)}")
        if build_settings.max_debit_per_trade is not None:
            parts.append(f"max loss ${build_settings.max_debit_per_trade:g}")
        if build_settings.marketable_limit_offset is not None:
            parts.append(f"entry +{int(round(build_settings.marketable_limit_offset * 100))}c")
        if build_settings.exit_target_percentages:
            targets = "/".join(f"{value:g}%" for value in build_settings.exit_target_percentages)
            parts.append(f"targets {targets}")
        if build_settings.allow_in_the_money_primary is not None:
            parts.append("ITM allowed" if build_settings.allow_in_the_money_primary else "ATM/OTM only")
    return " | ".join(parts) + "."


def _simulated_planner_config(config: OptionPlannerConfig) -> OptionPlannerConfig:
    target_delta = dict(config.target_delta_long)
    for label in ("0DTE", "1DTE", "2DTE", "3DTE", "THIS_FRIDAY", "NEXT_WEEK_FRIDAY"):
        target_delta[label] = [0.0, 1.0]
    return config.model_copy(
        deep=True,
        update={
            "quote_stale_after_seconds": 0,
            "min_open_interest": 0,
            "max_bid_ask_spread_percent": 10_000,
            "allow_in_the_money_primary": True,
            "min_debit_per_trade": 0,
            "max_debit_per_trade": max(config.max_debit_per_trade, 5_000),
            "expiries": list(dict.fromkeys([*config.expiries, "NEXT_WEEK_FRIDAY"])),
            "target_delta_long": target_delta,
        },
    )


def _simulated_replay_expiries(as_of_date: date) -> list[date]:
    expiries = [
        _add_business_days(as_of_date, 1),
        _next_friday_after(as_of_date),
    ]
    return list(dict.fromkeys(expiries))


def _mark_simulated_proposal(proposal: OptionProposal) -> OptionProposal:
    return proposal.model_copy(
        update={
            "id": f"sim_{proposal.id}",
            "reasons": list(
                dict.fromkeys(
                    [
                        "SIM_ONLY",
                        "historical_equity_replay",
                        "current_option_chain_contract_data",
                        *proposal.reasons,
                    ]
                )
            ),
            "notes": list(
                dict.fromkeys(
                    [
                        "SIMULATION ONLY - blocked from Schwab order submission.",
                        "Uses replayed underlying price with current Schwab option-chain contract data.",
                        *proposal.notes,
                    ]
                )
            ),
            "price_protection": f"SIM ONLY - {proposal.price_protection}".strip(),
        },
    )


def _simulated_fallback_proposals(
    record: SignalRecord,
    chain: Sequence[OptionContractSnapshot],
    metrics: TickerMetrics,
    scanned_at: datetime,
) -> list[OptionProposal]:
    right: OptionRight = "CALL" if record.payload.direction == "long" else "PUT"
    underlying = metrics.current_price or record.payload.underlying_price
    candidates = [
        contract
        for contract in chain
        if contract.right == right and _contract_entry_price(contract) is not None
    ]
    if not candidates:
        return []

    if underlying is None:
        contract = min(candidates, key=lambda item: (item.expiry, item.strike))
    else:
        contract = min(
            candidates,
            key=lambda item: (
                item.expiry,
                0
                if (item.right == "CALL" and item.strike >= underlying)
                or (item.right == "PUT" and item.strike <= underlying)
                else 1,
                abs(item.strike - underlying),
                item.strike if item.right == "CALL" else -item.strike,
            ),
        )

    entry_price = _contract_entry_price(contract)
    if entry_price is None:
        return []
    quantity = 1
    debit = round(entry_price * 100 * quantity, 2)
    leg = OptionProposalLeg(
        action="BUY",
        qty=quantity,
        symbol=contract.symbol,
        broker_symbol=contract.broker_symbol,
        expiry=contract.expiry,
        strike=contract.strike,
        right=contract.right,
        price=entry_price,
        bid=contract.bid,
        ask=contract.ask,
        mark=contract.mark,
        delta=contract.delta,
        open_interest=contract.open_interest,
        volume=contract.volume,
    )
    proposal_id_basis = "|".join(
        [
            record.id,
            "sim_fallback_single",
            contract.symbol,
            contract.expiry.isoformat(),
            f"{contract.strike:g}",
            contract.right,
        ]
    )
    proposal_id = f"sim_prop_{hashlib.sha256(proposal_id_basis.encode('utf-8')).hexdigest()[:12]}"
    return [
        OptionProposal(
            id=proposal_id,
            signal_id=record.id,
            symbol=contract.symbol,
            direction=record.payload.direction,
            structure="single",
            created_at=scanned_at,
            expiry=contract.expiry,
            quantity=quantity,
            underlying_price=underlying,
            legs=[leg],
            debit=debit,
            max_loss=debit,
            natural_limit_price=entry_price,
            natural_debit=debit,
            send_limit_price=entry_price,
            price_protection="SIM ONLY - replay proposal, not eligible for Schwab order submission.",
            net_delta=contract.delta,
            score=0,
            tos_order_line=_sim_tos_order_line(contract, quantity, entry_price),
            reasons=["SIM_ONLY", "historical_equity_replay", "simulated_fallback_single"],
            notes=[
                "SIMULATION ONLY - blocked from Schwab order submission.",
                "Fallback used nearest current option-chain contract to Friday replay underlying price.",
                f"Current-chain quote timestamp: {contract.timestamp.isoformat()}",
            ],
        )
    ]


def _contract_entry_price(contract: OptionContractSnapshot) -> float | None:
    for value in (contract.ask, contract.mark, contract.last):
        if value is not None and value > 0:
            return round(float(value), 2)
    return None


def _sim_tos_order_line(contract: OptionContractSnapshot, quantity: int, limit_price: float) -> str:
    return (
        f"SIM ONLY BUY +{quantity} SINGLE {contract.symbol.upper()} 100 "
        f"{contract.expiry.strftime('%d %b %y').upper()} {_format_strike(contract.strike)} "
        f"{contract.right} @{limit_price:.2f} LMT"
    )


def _target_intraday_date(candles: list[Candle], preferred: date, tz: ZoneInfo) -> date | None:
    dates = [candle.timestamp.astimezone(tz).date() for candle in candles]
    if not dates:
        return None
    if preferred in dates:
        return preferred
    return max(dates)


def _vwap(candles: list[Candle]) -> float | None:
    total_volume = sum(candle.volume for candle in candles)
    if total_volume <= 0:
        return None
    total = sum(((candle.high + candle.low + candle.close) / 3) * candle.volume for candle in candles)
    return total / total_volume


def _session(value: datetime, timezone_name: str) -> ScanSession:
    local = value.astimezone(ZoneInfo(timezone_name))
    clock = local.time().replace(tzinfo=None)
    weekday = local.weekday()
    if weekday == 5:
        return "closed"
    if weekday == 6:
        return "overnight" if clock >= time(20, 0) else "closed"
    if weekday < 4 and clock >= time(20, 0):
        return "overnight"
    if weekday <= 4 and clock < time(4, 0):
        return "overnight"
    if weekday == 4 and clock >= time(20, 0):
        return "closed"
    if time(4, 0) <= clock < time(9, 30):
        return "premarket"
    if time(9, 30) <= clock < time(16, 0):
        return "regular"
    if time(16, 0) <= clock < time(20, 0):
        return "after_hours"
    return "closed"


def _data_freshness_notes(*, as_of: datetime, price_time: datetime | None, session: ScanSession) -> list[str]:
    if price_time is None:
        return ["missing_price_timestamp"]
    age_seconds = max(0, int((as_of - price_time).total_seconds()))
    if session == "overnight" and age_seconds > 900:
        return [
            f"stale_overnight_price:{price_time.isoformat()}",
            "schwab_rest_may_not_match_tos_24h_price",
        ]
    if session in {"premarket", "regular", "after_hours"} and age_seconds > 900:
        return [f"stale_price:{price_time.isoformat()}"]
    return []


def _scan_id(value: datetime) -> str:
    return value.strftime("scan_%Y%m%d_%H%M%S")


def _utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def _round(value: float | int | None, places: int = 4) -> float | None:
    return None if value is None else round(float(value), places)


def _format_strike(strike: float) -> str:
    return str(int(strike)) if float(strike).is_integer() else str(strike)


def _add_business_days(as_of_date: date, days: int) -> date:
    if days <= 0:
        return as_of_date
    current = as_of_date
    remaining = days
    while remaining > 0:
        current += timedelta(days=1)
        if current.weekday() < 5:
            remaining -= 1
    return current


def _next_friday_after(as_of_date: date) -> date:
    days_until_friday = (4 - as_of_date.weekday()) % 7
    if days_until_friday == 0:
        days_until_friday = 7
    return as_of_date + timedelta(days=days_until_friday)
