from __future__ import annotations

import hashlib
from datetime import date, datetime, time, timezone
from zoneinfo import ZoneInfo

from nt_schwab_bridge.config import OptionPlannerConfig
from nt_schwab_bridge.models import SignalPayload, SignalRecord
from nt_schwab_bridge.planner import OptionProposalPlanner
from nt_schwab_bridge.schwab_adapter import SchwabApiError, SchwabOptionChainProvider

from market_scanner.config import AppSettings
from market_scanner.models import (
    Bias,
    Candle,
    CandidateAction,
    EquityQuote,
    MarketRegime,
    RegimeSymbolState,
    ScanResult,
    ScanSession,
    ScannerCandidate,
    TickerMetrics,
)
from market_scanner.schwab_ext import SchwabEquityDataClient


class MarketScanner:
    def __init__(
        self,
        settings: AppSettings,
        equity_client: SchwabEquityDataClient | None = None,
    ) -> None:
        self.settings = settings
        self.equity_client = equity_client or SchwabEquityDataClient(settings.schwab)
        self.planner_config: OptionPlannerConfig = settings.planner_config()
        self.planner = OptionProposalPlanner(self.planner_config)
        self.option_provider = SchwabOptionChainProvider(
            client=self.equity_client.raw_client,
            planner_config=self.planner_config,
        )

    def scan(self, as_of: datetime | None = None) -> ScanResult:
        scanned_at = _utc(as_of or datetime.now(timezone.utc))
        all_symbols = list(dict.fromkeys([*self.settings.scanner.regime_symbols, *self.settings.scanner.symbols]))
        quotes = self._safe_quotes(all_symbols)
        metrics_by_symbol = {
            symbol: self._safe_metrics(symbol, quotes.get(symbol), scanned_at)
            for symbol in all_symbols
        }
        regime = self._market_regime(metrics_by_symbol)
        candidates = [
            self._candidate(symbol, metrics_by_symbol[symbol], regime, scanned_at)
            for symbol in self.settings.scanner.symbols
        ]
        ranked = sorted(candidates, key=lambda item: item.score, reverse=True)
        top = ranked[: self.settings.scanner.top_n]
        return ScanResult(
            scan_id=_scan_id(scanned_at),
            scanned_at=scanned_at,
            session=_session(scanned_at, self.settings.scanner.timezone),
            universe=self.settings.scanner.symbols,
            regime=regime,
            candidates=ranked,
            top_candidates=top,
            notes=[
                "Generated by Schwab Market Scanner.",
                "Option ideas are proposals only; live orders require explicit gated send confirmation.",
            ],
        )

    def _safe_quotes(self, symbols: list[str]) -> dict[str, EquityQuote]:
        try:
            return self.equity_client.get_quotes(symbols)
        except Exception:
            quotes: dict[str, EquityQuote] = {}
            for symbol in symbols:
                try:
                    quotes[symbol] = self.equity_client.get_quote(symbol)
                except Exception:
                    continue
            return quotes

    def _safe_metrics(self, symbol: str, quote: EquityQuote | None, as_of: datetime) -> TickerMetrics:
        notes: list[str] = []
        try:
            intraday = self.equity_client.get_intraday_candles(symbol)
        except Exception as exc:
            intraday = []
            notes.append(f"intraday_unavailable:{exc.__class__.__name__}")
        try:
            daily = self.equity_client.get_daily_candles(symbol)
        except Exception as exc:
            daily = []
            notes.append(f"daily_unavailable:{exc.__class__.__name__}")
        metrics = compute_metrics(
            symbol=symbol,
            quote=quote,
            intraday=intraday,
            daily=daily,
            as_of=as_of,
            timezone_name=self.settings.scanner.timezone,
        )
        metrics.data_notes.extend(notes)
        return metrics

    def _market_regime(self, metrics_by_symbol: dict[str, TickerMetrics]) -> MarketRegime:
        states: list[RegimeSymbolState] = []
        for symbol in self.settings.scanner.regime_symbols:
            metrics = metrics_by_symbol.get(symbol) or TickerMetrics(symbol=symbol)
            score, bias, reasons = _regime_score(metrics)
            states.append(RegimeSymbolState(symbol=symbol, bias=bias, score=score, metrics=metrics, reasons=reasons))
        if not states:
            return MarketRegime(bias="unknown", score=0, symbols=[], reasons=["no_regime_symbols"])
        avg = sum(state.score for state in states) / len(states)
        if avg >= 0.75:
            bias: Bias = "bullish"
        elif avg <= -0.75:
            bias = "bearish"
        else:
            bias = "mixed"
        return MarketRegime(
            bias=bias,
            score=round(avg, 4),
            symbols=states,
            reasons=[f"{state.symbol}:{state.bias}:{state.score:g}" for state in states],
        )

    def _candidate(
        self,
        symbol: str,
        metrics: TickerMetrics,
        regime: MarketRegime,
        scanned_at: datetime,
    ) -> ScannerCandidate:
        action, direction, reasons, warnings = classify_candidate(
            metrics,
            regime,
            min_price=self.settings.scanner.min_price,
            min_abs_gap_pct=self.settings.scanner.min_abs_gap_pct,
            min_premarket_volume=self.settings.scanner.min_premarket_volume,
        )
        score = candidate_score(metrics, action, regime)
        proposals = []
        blocked: list[str] = []
        if direction in {"long", "short"}:
            try:
                record = _signal_record(symbol, direction, metrics, scanned_at)
                chain = list(self.option_provider(record))
                underlying = self.option_provider.last_underlying_price or metrics.current_price
                result = self.planner.plan(record, chain, scanned_at, underlying_price=underlying)
                proposals = result.proposals
                blocked = result.blocked_reasons
            except (SchwabApiError, RuntimeError) as exc:
                blocked = [f"proposal_generation_error:{exc.__class__.__name__}:{str(exc)[:120]}"]
        return ScannerCandidate(
            rank=0,
            symbol=symbol,
            action=action,
            direction=direction,
            score=score,
            metrics=metrics,
            reasons=reasons,
            warnings=warnings,
            proposals=proposals,
            proposal_blocked_reasons=blocked,
        )


def compute_metrics(
    *,
    symbol: str,
    quote: EquityQuote | None,
    intraday: list[Candle],
    daily: list[Candle],
    as_of: datetime,
    timezone_name: str,
) -> TickerMetrics:
    tz = ZoneInfo(timezone_name)
    local_as_of = as_of.astimezone(tz)
    daily_sorted = sorted(daily, key=lambda item: item.timestamp)
    intraday_sorted = sorted(intraday, key=lambda item: item.timestamp)
    complete_daily = [
        candle
        for candle in daily_sorted
        if candle.timestamp.astimezone(tz).date() < local_as_of.date()
    ]
    if not complete_daily and daily_sorted:
        complete_daily = daily_sorted[:-1] or daily_sorted
    previous = complete_daily[-1] if complete_daily else None
    sma_source = complete_daily[-200:] if len(complete_daily) >= 200 else complete_daily
    sma200 = sum(candle.close for candle in sma_source) / len(sma_source) if sma_source else None

    target_date = _target_intraday_date(intraday_sorted, local_as_of.date(), tz)
    day_bars = [
        candle
        for candle in intraday_sorted
        if target_date is not None and candle.timestamp.astimezone(tz).date() == target_date
    ]
    premarket_bars = [
        candle
        for candle in day_bars
        if time(4, 0) <= candle.timestamp.astimezone(tz).time().replace(tzinfo=None) < time(9, 30)
    ]
    regular_bars = [
        candle
        for candle in day_bars
        if time(9, 30) <= candle.timestamp.astimezone(tz).time().replace(tzinfo=None) < time(16, 0)
    ]
    usable_bars = day_bars or intraday_sorted
    latest = usable_bars[-1] if usable_bars else None
    quote_price = quote.last if quote and quote.last and quote.last > 0 else None
    current_price = quote_price or (latest.close if latest else None)
    gap_pct = (
        ((current_price - previous.close) / previous.close) * 100
        if current_price is not None and previous is not None and previous.close
        else None
    )
    bid = quote.bid if quote else None
    ask = quote.ask if quote else None
    spread_pct = None
    if bid is not None and ask is not None and ask >= bid and current_price:
        spread_pct = ((ask - bid) / current_price) * 100

    return TickerMetrics(
        symbol=symbol.upper(),
        target_date=target_date,
        current_price=_round(current_price),
        previous_close=_round(previous.close if previous else None),
        previous_high=_round(previous.high if previous else None),
        previous_low=_round(previous.low if previous else None),
        sma200=_round(sma200),
        gap_pct=_round(gap_pct),
        premarket_high=_round(max((bar.high for bar in premarket_bars), default=None)),
        premarket_low=_round(min((bar.low for bar in premarket_bars), default=None)),
        premarket_volume=sum(bar.volume for bar in premarket_bars),
        today_high=_round(max((bar.high for bar in regular_bars), default=None)),
        today_low=_round(min((bar.low for bar in regular_bars), default=None)),
        vwap=_round(_vwap(day_bars)),
        bid=_round(bid),
        ask=_round(ask),
        spread_pct=_round(spread_pct),
        latest_bar_time=latest.timestamp if latest else None,
        data_notes=[],
    )


def classify_candidate(
    metrics: TickerMetrics,
    regime: MarketRegime,
    *,
    min_price: float,
    min_abs_gap_pct: float,
    min_premarket_volume: int,
) -> tuple[CandidateAction, str, list[str], list[str]]:
    reasons: list[str] = []
    warnings: list[str] = []
    if metrics.current_price is None or metrics.previous_close is None or metrics.gap_pct is None:
        return "AVOID", "none", ["missing_price_or_gap_data"], metrics.data_notes
    if metrics.current_price < min_price:
        return "AVOID", "none", [f"price_below_min:{metrics.current_price:g}<{min_price:g}"], metrics.data_notes
    if abs(metrics.gap_pct) < min_abs_gap_pct:
        return "WATCH", "none", [f"gap_below_min:{metrics.gap_pct:g}%"], metrics.data_notes
    if metrics.premarket_volume < min_premarket_volume:
        warnings.append(f"premarket_volume_below_min:{metrics.premarket_volume}<{min_premarket_volume}")

    if metrics.gap_pct > 0:
        reasons.append("gap_up")
        if metrics.current_price and metrics.previous_high and metrics.current_price > metrics.previous_high:
            reasons.append("above_previous_high")
        if metrics.sma200 and metrics.previous_close and metrics.previous_close > metrics.sma200:
            reasons.append("previous_close_above_sma200")
        if regime.bias == "bearish":
            warnings.append("market_regime_bearish_against_call")
            return "WATCH", "none", reasons, warnings
        return "CALL_BIAS", "long", reasons, warnings

    reasons.append("gap_down")
    if metrics.current_price and metrics.previous_low and metrics.current_price < metrics.previous_low:
        reasons.append("below_previous_low")
    if regime.bias == "bullish":
        warnings.append("market_regime_bullish_against_put")
        return "WATCH", "none", reasons, warnings
    return "PUT_BIAS", "short", reasons, warnings


def candidate_score(metrics: TickerMetrics, action: CandidateAction, regime: MarketRegime) -> float:
    base = abs(metrics.gap_pct or 0) * 10
    volume_score = min(25.0, (metrics.premarket_volume or 0) / 20_000)
    action_bonus = 20.0 if action in {"CALL_BIAS", "PUT_BIAS"} else 0.0
    regime_bonus = 5.0 if regime.bias != "mixed" else 0.0
    return round(base + volume_score + action_bonus + regime_bonus, 4)


def _regime_score(metrics: TickerMetrics) -> tuple[float, Bias, list[str]]:
    score = 0.0
    reasons: list[str] = []
    if metrics.current_price is None or metrics.previous_close is None:
        return 0, "unknown", ["missing_regime_price"]
    if metrics.current_price > metrics.previous_close:
        score += 1
        reasons.append("above_previous_close")
    elif metrics.current_price < metrics.previous_close:
        score -= 1
        reasons.append("below_previous_close")
    if metrics.vwap:
        if metrics.current_price > metrics.vwap:
            score += 0.5
            reasons.append("above_vwap")
        elif metrics.current_price < metrics.vwap:
            score -= 0.5
            reasons.append("below_vwap")
    if metrics.premarket_high and metrics.current_price > metrics.premarket_high:
        score += 0.5
        reasons.append("above_premarket_high")
    if metrics.premarket_low and metrics.current_price < metrics.premarket_low:
        score -= 0.5
        reasons.append("below_premarket_low")
    if score >= 0.75:
        return round(score, 4), "bullish", reasons
    if score <= -0.75:
        return round(score, 4), "bearish", reasons
    return round(score, 4), "mixed", reasons


def _signal_record(symbol: str, direction: str, metrics: TickerMetrics, scanned_at: datetime) -> SignalRecord:
    payload = SignalPayload(
        strategy="SchwabMarketScanner",
        symbol=symbol,
        direction=direction,
        qty=1,
        underlying_price=metrics.current_price,
        timeframe="1m",
        timestamp=scanned_at,
        signal_type="scanner_gap",
        source_indicator="premarket_gap_scanner",
        tags=["scanner", "gap", direction],
        notes=", ".join(metrics.data_notes),
    )
    signal_id = hashlib.sha256(f"{symbol}|{direction}|{scanned_at.isoformat()}".encode("utf-8")).hexdigest()[:12]
    return SignalRecord(
        id=f"scan_{signal_id}",
        payload=payload,
        received_at=scanned_at,
        execution_mode="dry_run",
    )


def _target_intraday_date(candles: list[Candle], preferred: date, tz: ZoneInfo) -> date | None:
    dates = [candle.timestamp.astimezone(tz).date() for candle in candles]
    if not dates:
        return None
    if preferred in dates:
        return preferred
    return max(dates)


def _vwap(candles: list[Candle]) -> float | None:
    total_volume = sum(candle.volume for candle in candles)
    if total_volume <= 0:
        return None
    total = sum(((candle.high + candle.low + candle.close) / 3) * candle.volume for candle in candles)
    return total / total_volume


def _session(value: datetime, timezone_name: str) -> ScanSession:
    local = value.astimezone(ZoneInfo(timezone_name))
    clock = local.time().replace(tzinfo=None)
    if local.weekday() >= 5:
        return "closed"
    if time(4, 0) <= clock < time(9, 30):
        return "premarket"
    if time(9, 30) <= clock < time(16, 0):
        return "regular"
    if time(16, 0) <= clock < time(20, 0):
        return "after_hours"
    return "closed"


def _scan_id(value: datetime) -> str:
    return value.strftime("scan_%Y%m%d_%H%M%S")


def _utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def _round(value: float | int | None, places: int = 4) -> float | None:
    return None if value is None else round(float(value), places)
